config/routes.rb
Rails.application.routes.draw do

  resources :users, except: :index
  resources :posts do
    resources :comments, only: :create
  end
  get "/signup" => "users#new"
  get "/profile" => "users#show"
  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"

  root 'static_pages#home'

end

app/models/comment.rb
class Comment
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :body, type: String

  def date_added
  	self.created_at.localtime.strftime("%-m/%-d/%Y | %l:%M %p")
  end

  #validating body is present
  validates :body, presence: true

  embedded_in :post
end

app/models/post.rb
class Post
  include Mongoid::Document
  include Mongoid::Timestamps
  include Geocoder::Model::Mongoid

  field :title, type: String
  field :dog_breed, type: String
  field :body, type: String
  field :url, type: String
  field :coordinates, :type => Array
  field :address, :type => String


  mount_uploader :image, AvatarUploader

  def date_added
  	self.created_at.localtime.strftime("%-m/%-d/%Y | %l:%M %p")
  end

  # Geocoder validation
  geocoded_by :address               # can also be an IP address
  # after_validation :geocode          # auto-fetch coordinates
  after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }

  #validating post body is present
  validates :title, presence: true
  validates :body, presence: true
  validates :address, presence: true

  belongs_to :user
  embeds_many :comments
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps

  field :user_name, type: String
  field :name, type: String
  field :email, type: String
  mount_uploader :avatar, AvatarUploader
  field :password_digest, type: String
  attr_reader :password

  #setter method
  def password=(unencrypted_password)
    unless unencrypted_password.empty?
      @password = unencrypted_password
      self.password_digest = BCrypt::Password.create(unencrypted_password)
    end
  end

  def authenticate(unencrypted_password)
    if BCrypt::Password.new(self.password_digest) == unencrypted_password
      return self
    else
      return false
    end
  end

  # Validating name, email and password
  validates :user_name, presence: true, uniqueness: true, on: :create
  validates :name, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validates :password, presence: true, length: { :within => 6..40 }, confirmation: true, :allow_blank => false, :on => :create
  validates :password, presence: true, length: { :within => 6..40 }, confirmation: true, :allow_blank => true, :on => :update
  

  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #include SessionsHelper
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		post = Post.find(params[:post_id])
		comment = post.comments.create(comment_params)
		redirect_to post_path(comment.post)
	end

	private
	def comment_params
		params.require(:comment).permit(:body)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
include PostsHelper
  def index
  	@posts = Post.all
  end

  def new
  	@post = Post.new
  end

	def edit
		# this action is responsible for retrieving a specific bean
		@post = Post.find(params[:id])
		@post.user = current_user
	end

  def create
  	@post = Post.new(post_params)
  	@post.user = current_user
		# if the new post creation & save is sucessful, we want to redirect to the index
		if @post.save
			redirect_to posts_path
		else
			#if unsuccessful, reset to the new page
			render "new"
		end
  end

  def show
  	@post = Post.find(params[:id])
  	# Adding new comments to be posted onto a single post
  	@comment = Comment.new
  	address = @post.address
  	google_maps(address)
  end

  def update # this action is responsible for saving an update to a specific post
		# Retrieving a specific post from the database
		@post = Post.find(params[:id])

		if @post.update_attributes(params.require(:post).permit(:title, :dog_breed, :body))
			redirect_to posts_path
		else
			#if unsuccessful, show to the edit page
			render "edit"
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to posts_path
	end

  private
		def post_params
		 	params.require(:post).permit(:title, :dog_breed, :body, :user, :image, :coordinates, :address, :geocode)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:login][:email]) unless params[:login][:email].empty?
    if user && user.authenticate(params[:login][:password])
      session[:user_id] = user.id.to_s
      redirect_to user_path(current_user)
    else
      render "sessions/new", alert: 'Unable to login'
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to login_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all
  end

  def new
  	@user = User.new
  end

  def edit
  	@user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id.to_s
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  def show
  	@user = User.find(params[:id])
  end

  def update # this action is responsible for saving an update to a specific user
	# Retrieving a specific user from the database
		@user = User.find(params[:id])

		if @user.update_attributes(user_params)
			redirect_to user_path, alert: 'Profile Successfully Updated'
		else
		#if unsuccessful, show to the edit page
		render "edit", alert: 'Unable to update Profile'
	 end
  end

  def destroy
  	@user = User.find(params[:id])
  	@user = current_user.destroy
    session.delete(:user_id)
  	redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :name, :email, :avatar, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper


		def google_maps(address)
			address = address.gsub " ","+"
			map_api = ENV["GOOGLE_MAP_API"]
			@map = "https://www.google.com/maps/embed/v1/place?key=#{map_api}&q=#{address}"
  	end
	

end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find(session[:user_id])
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dog Finder</title>
  <%= favicon_link_tag "favicon.ico" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
	<div class="container-fluid">
		<div id="main-container" class="container">
			<%= render 'shared/navigation' %>

	    	<%= yield %>

		</div>
	</div>
</body>
</html>

app/views/posts/edit.html.erb
<div class="row">
	<div class="col-md-10">
		<h1>Edit your Post!</h1>

		<div class="row">
			<div class="col-md-10 form-group">
				<%= simple_form_for @post do |f| %>
					<%= f.input :title, placeholder: 'Report Title', :class => "form-control" %>
					<%= f.input :dog_breed, placeholder: 'Dog Breed', :class => "form-control" %>	
					<%= f.text_area :body, placeholder: 'Report Body', :class => "form-control" %>
					<%= f.file_field :image, placeholder: 'Add/Update an Image' %>
					<br />
					<%= f.submit "Update Post", :class => "btn btn-primary col-md-2" %>
				<% end %>
			</div>
		</div>
		<%= link_to "Back to the list!", posts_path %>
	</div>
</div>

app/views/posts/index.html.erb
<div class="row">
	<div class="col-lg-12">
		<h1 class="centered">Reported Lost Pets!</h1>
		<hr>
			<div class="row">
				<div class="col-lg-6 col-lg-offset-4">
			<% @posts.each do |p| %>
				<p>
				<strong><%= p.title %></strong> -- <%= p.body %> 
				<%= link_to "More info", post_path(p) %>
				</p>
			<% end %>
			</div>
			</div>
	</div>
</div>

<div class="row centered">
	<div class="col-lg-6 col-lg-offset-3">
		<% if current_user %>
			<%= link_to new_post_path, class: 'btn btn-primary' do %>
		  	<i class="glyphicon glyphicon-plus"></i> Add a lost/stranded pet
				<% end %>
			<% else %>
				<%= link_to new_user_path, class: 'btn btn-primary' do %>
  			<i class="glyphicon glyphicon-plus"></i> Sign Up to report a lost or stranded pet!
				<% end %>
		<% end %>
	</div>
</div>

app/views/posts/new.html.erb
<div class="row">
	<h1 class="centered">Let's find your Dog!</h1>
</div>

<div class="row">
	<div class="col-md-8 col-md-offset-2 form-group">

		<ul>
		  <% @post.errors.full_messages.each do |msg| %>
		    <li><%= msg %></li>  
		  <% end %>
		</ul>
		<%= simple_form_for @post do |f| %>

			<%= f.input :title, placeholder: 'Post Title', :class => "form-control" %>
			<div>
			<%= f.label :dog_breed, "Dog Breed" %><br />
			<%= f.select :dog_breed, options_from_collection_for_select(DOG_BREED, "to_s", "to_s"), :class => "form-control" %>
			</div>
			<br />
			<%= f.input :address, placeholder: 'Address', :class => "form-control" %>
			<%= f.text_area :body, placeholder: 'Report', :class => "form-control" %>
			<br />
			<%= f.file_field :image %>
			<br />

			<%= f.submit "Let's find your pet!", :class => "btn btn-primary col-md-3" %>
		<% end %>
	</div>
</div>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <h2 class="centered">Let's find that lost pooch!</h2>
    <div class="row">
      <div class="col-md-12">
        <div class="col-md-6">
          <h4>Report Title: <%= @post.title %></h4>
          <h4>Report: <%= @post.body %>.</h4>
          <h4>Breed: <%= @post.dog_breed %>.</h4>
          <% if current_user %>
            <p>Added by <%= @post.user.name %> -- <%= @post.date_added %> </p>
          <% end %>
            <p><%= image_tag @post.image.url(:small) if @post.image.url(:small).present? %></p>

          <section>
              <h4>Comments:</h4>

              <div>
                  <% @post.comments.each do |comment| %>        
                      <div>
                          <p><%= comment.body %> -- added by: <%= comment.date_added %></p>
                      </div>
                  <% end %>
              </div>
          </section>

          <section>
              <h4>Add a new comment</h4>
                  <ul>
                      <% @comment.errors.full_messages.each do |msg| %>
                      <li><%= msg %></li>  
                      <% end %>
                  </ul>    
              <%= simple_form_for [@post, @comment] do |f| %>
                  <div>
                    <%= f.text_area :body, :class => "form-control" %>
                  </div><br />
                  <%= f.submit "Add a comment!", :class => 'btn' %>

              <% end %>
              <br />
          </section>
        
          <div class="row">
            <div class="col-md-12">
              <% if current_user != nil && 
                  current_user.id == @post.user.id %>
                  <%=  link_to "Edit your post!", edit_post_path, :class => 'btn btn-primary'  %>
                  <%= link_to "Delete this post!", :post, method: :delete, data: { confirm: "Are you sure you want to delete your post?" }, :class => 'btn btn-primary'  %>
                  <%= link_to "Back to the Reports!", posts_path, :class => 'btn btn-primary'  %>
              <% else %>
                  <%= link_to "Back to the Reports!", posts_path, :class => 'btn btn-primary'  %>
              <% end %>
            </div>
          </div>

          
        </div>
        <div class="col-md-6">
          <h4 class="centered">Last seen at:</h4>
          <div id="map-container">
            <div id="map-canvas">
              <iframe id="map-canvas" src="<%= @map %>"></iframe>
            </div>
          </div>
        </div>
      </div>
    </div> 
  </div>
</div>

app/views/shared/_footer.html.erb
<!-- FOOTER -->
<div class="navbar navbar-fixed-bottom footer">
	<div class="container">
		<div class="row centered">
			<div class="col-lg-4" >
			<a href="#"><i class="fa fa-twitter"></i></a>
			</div>
			<div class="col-lg-4" >
			<a href="#"><i class="fa fa-facebook"></i></a>
			</div>
			<div class="col-lg-4" >
			<a href="#"><i class="fa fa-dribbble"></i></a>
			</div>	
		</div><!-- row -->
	</div><!-- container -->
</div><!-- Footer -->

app/views/shared/_navigation.html.erb
<!-- Fixed navbar -->
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">D<i class="fa fa-circle"></i>G Finder</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="active"><a href="/">HOME</a></li>
        <li><a href="/posts">Lost Pet Reports</a></li>
        <% if current_user %>
          <li><a href="/posts/new">New Post</a></li>
          <li><%= link_to "Profile", user_path(current_user) %></li>
          <li><%= link_to "Log out!", logout_path, method: :delete %></li>
        <% else %>
          <li><a href="/users/new">Sign Up</a></li>
          <li><%= link_to "Log in!", login_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="row">
	<div id="headerwrap">
		<div class="col-lg-8 col-lg-offset-2 img-responsive">
			<h1>D<i class="fa fa-circle"></i>G Finder</h1>
			<h2>Because No One Gets Left Behind</h2>
		</div>
	</div><!-- headerwrap -->
</div><!-- row -->

<br>

<div class="row centered w">
	<div class="col-lg-4">
		<i class="fa fa-heart"></i>
		<h4>DESIGN</h4>
		<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even believable.</p>
	</div><!-- col-lg-4 -->

	<div class="col-lg-4">
		<i class="fa fa-laptop"></i>
		<h4>BOOTSTRAP</h4>
		<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even believable.</p>
	</div><!-- col-lg-4 -->

	<div class="col-lg-4">
		<i class="fa fa-trophy"></i>
		<h4>SUPPORT</h4>
		<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even believable.</p>
	</div><!-- col-lg-4 -->
</div><!-- row -->

<br>

<!-- FEATURE SECTION -->
<div class="row centered wb">
	<div class="col-lg-12">
		<h4>WE CREATE FIRST CLASS DESIGN</h4>
		<p>By being true to the brand we represent, we elevate the audiences’ relationship to it. Like becomes love becomes a passion. Passion becomes advocacy. And we see the brand blossom from within, creating a whole story the audience embraces. That’s when the brand can truly flex its muscles.</p>
		<p><br/></p>
	</div>

</div><!-- row -->



	<div id="light_gray">

			<div class="row centered">
				<h4>OUR AWESOME SPONSORS</h4>
				<div class="col-lg-2 col-lg-offset-1">
					<%= image_tag "https://s3-us-west-1.amazonaws.com/dogfinderapp/peta_logo.png" %>
				</div>
				<div class="col-lg-2">
					<%= image_tag "https://s3-us-west-1.amazonaws.com/dogfinderapp/home_again.png" %>
				</div>
				<div class="col-lg-2">
					<%= image_tag "https://s3-us-west-1.amazonaws.com/dogfinderapp/humaine_society.png" %>
				</div>
				<div class="col-lg-2">
					<%= image_tag "https://s3-us-west-1.amazonaws.com/dogfinderapp/dogs_for_life_logo.png" %>
				</div>
				<div class="col-lg-2">
					<%= image_tag "https://s3-us-west-1.amazonaws.com/dogfinderapp/aspca_logo.png" %>
				</div>
			</div><!-- row -->

	</div><!-- dg -->
	
	
	<div id="r">
		<div class="container">
			<div class="row centered">
				<div class="col-lg-8 col-lg-offset-2">
					<h4>WE ARE STORYTELLERS. BRANDS ARE OUR SUBJECTS. DESIGN IS OUR VOICE.</h4>
					<p>We believe ideas come from everyone, everywhere. At BlackTie, everyone within our agency walls is a designer in their own right. And there are a few principles we believe—and we believe everyone should believe—about our design craft. These truths drive us, motivate us, and ultimately help us redefine the power of design.</p>
				</div>
			</div><!-- row -->
		</div><!-- container -->
	</div><!-- r wrap -->

app/views/users/edit.html.erb
<div class="row">
	<div class="col-md-10">
		<h1>Edit your profile!</h1>

		<div class="row">
			<div class="col-md-10 form-group">
				<%= simple_form_for @user do |f| %>
					<%= f.input :user_name, placeholder: 'User Name', :class => "form-control" %>		
					<%= f.input :name, placeholder: 'First & Last Name', :class => "form-control" %>
					<%= f.input :email, placeholder: 'Email', :class => "form-control" %>
					<%= f.file_field :avatar, placeholder: 'Add/Update an Image' %>
					<br />
					<%= f.submit "Update Profile", :class => "btn btn-primary col-md-2" %>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<h1>Users</h1>

<ul>
	<% @users.each do |user| %>

		<li>
			<%= user.name %> <%= link_to "More info", user_path(user) %>
		</li>

	<% end %>
	
</ul>

app/views/users/new.html.erb
<div class="row">
	<h1 class="centered">Sign Up for an Account</h1>
</div>

<div class="row">
	<div class="col-md-8 col-md-offset-2 form-group">

		<ul>
		  <% @user.errors.full_messages.each do |msg| %>
		    <li><%= msg %></li>  
		  <% end %>

		</ul>

		<%= simple_form_for @user do |f| %>
				
				<%= f.input :user_name, placeholder: 'User Name', :class => "form-control" %>		
				<%= f.input :name, placeholder: 'First & Last Name', :class => "form-control" %>
				<%= f.input :email, placeholder: 'Email', :class => "form-control" %>
				<%= f.input :password, placeholder: 'Password', :class => "form-control" %>
				<%= f.input :password_confirmation, placeholder: 'Confirm Your Password', :class => "form-control" %>
				<div>
				<%= f.file_field :avatar, placeholder: 'Add an Image' %>
				</div>
				<br />
			<%= f.submit "Sign Up!", :class => "btn btn-primary col-md-2" %>
			<br />
			<br />

		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<div class="row">
	
	<div class="col-md-10 col-md-offset-2" >

		<h1><%= current_user.name %></h1>

		<div class="row">
			
			<div class="col-md-6">
				<p><%= image_tag @user.avatar.url(:small) if @user.avatar.url(:small).present? %></p>
			</div>
			
			<div class="col-md-4">
			
				<div class="row">
				<p>First &amp; Last Name: <%= current_user.name %></p>
				</div>
			
				<div class="row">
				<p>Email: <%= current_user.email %></p>
				</div>
			
				<div class="row">
					<p>Reports:<br />
						<ul>
							<% @user.posts.each do |p| %>
								<li><strong><%= p.title %></strong>
									<%= link_to "View Post", post_path(p) %>
								</li>
							<% end %>
						</ul>
					</p>
				</div>

			</div>
		</div>

		<%= link_to "Add a report", new_post_path, :class => 'btn btn-primary' %>
		<%= link_to "Update your profile!", edit_user_path, :class => 'btn btn-primary'  %>
		<%= link_to "Delete your profile!", :user, method: :delete, data: { confirm: "Are you sure you want to delete your profile?" }, :class => 'btn btn-primary'  %>
	</div>
</div>